# Project
group = dev.tophatcat.mysteriousbiomes
mod_name = Mysterious Biomes
mod_id = mysteriousbiomes
author = KiriCattus
credits = KiriCattus
license = LGPL-v2.1
license_description = A Minecraft mod made for SpookyJam 2017, contains Halloween themed biomes and content.
description = A mod made during SpookyJam 2017, Mysterious Biomes is a bundle of some spooky and miscellaneous nice to have biomes and content to enhance your Minecraft gameplay!

# Links
display_url = https://tophatcat.dev
discord = https://discord.tophatcat.dev
mod_source = https://github.com/kiris-mods/mysterious-biomes
license_url = https://github.com/kiris-mods/mysterious-biomes/blob/dev/LICENSE.md
modrinth_url = https://modrinth.com/mod/mysterious-biomes
curseforge_url = https://www.curseforge.com/minecraft/mc-mods/mysterious-biomes

# Common
java_version = 21
minecraft_version = 1.21.10
parchment_minecraft = 1.21.10
parchment_version = 2025.10.12
modrinth_id = SrAIvfzS
curseforge_id = 280003

# NeoForge
# See https://projects.neoforged.net/ for new versions
# See https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
neoforge_version = 21.10.17-beta
neo_form_version = 1.21.10-20251010.172816

moddev_version = 2.0.115
licenser_version = 0.7.5

# Fabric
# See https://fabricmc.net/develop/ for new versions
fabric_loom = 1.12.0-alpha.40
fabric_version = 0.135.0
fabric_loader_version = 0.17.3

# Dependencies
# - Common
smart_brain_lib_common_version = 1.16.11
geckolib_common_version = 5.3-alpha-1
# TODO Update this once it's released.
# resourceful_config_common_version = 3.0.8
terrablender_common_version = 21.10.0.0

# - NeoForge
smart_brain_lib_neoforge_version = 1.16.11
geckolib_neoforge_version = 5.3-alpha-1
# TODO Update this once it's released.
# resourceful_config_neoforge_version = 3.0.8
terrablender_neoforge_version = 21.10.0.0
# -- Optional
jade_neoforge_version = 20.0.5

# - Fabric
smart_brain_lib_fabric_version = 1.16.11
geckolib_fabric_version = 5.3-alpha-1
# TODO Update this once it's released.
# resourceful_config_fabric_version = 3.0.8
terrablender_fabric_version = 21.10.0.0
# -- Optional
jade_fabric_version = 20.0.5
modmenu_version = 16.0.0-rc.1

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.debug = false
org.gradle.configuration-cache = true
org.gradle.parallel = true
