pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "NeoForge"
            url = "https://maven.neoforged.net"
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Fabric"
                    url = "https://maven.fabricmc.net"
                }
            }
            filter {
                includeGroupAndSubgroups("net.fabricmc")
                includeGroup("fabric-loom")
            }
        }
    }

    includeBuild("build-logic")
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

// This should match the mod ID so that the published coordinates can be sensible
rootProject.name = "mysteriouslands"
include(":${rootProject.name}-common")
project(":${rootProject.name}-common").projectDir = file("common")
include(":${rootProject.name}-fabric")
project(":${rootProject.name}-fabric").projectDir = file("fabric")
include(":${rootProject.name}-neoforge")
project(":${rootProject.name}-neoforge").projectDir = file("neoforge")
